OPTIMIZE TABLE
activepropertybusinessmodel,
activepropertylist         ,
airportcoordinateslist     ,
aliasregionlist            ,
areaattractionslist        ,
attributelist              ,
chainlist                  ,
citycoordinateslist        ,
countrylist                ,
diningdescriptionlist      ,
hotelimagelist             ,
log_activeproperty_changes ,
neighborhoodcoordinateslist,
oldactivepropertylist      ,
parentregionlist           ,
pointsofinterestcoordinateslist,
policydescriptionlist          ,
propertyamenitieslist          ,
propertyattributelink          ,
propertybusinessamenitieslist  ,
propertydescriptionlist        ,
propertyfeeslist               ,
propertylocationlist           ,
propertymandatoryfeeslist      ,
propertynationalratingslist    ,
propertyrenovationslist        ,
propertyroomslist              ,
propertytypelist               ,
recreationdescriptionlist      ,
regioncentercoordinateslist    ,
regioneanhotelidmapping        ,
roomtypelist                   ,
spadescriptionlist             ,
trainmetrostationcoordinateslist,
whattoexpectlist                ;
